<a href="https://colab.research.google.com/github/Cothilyba77/Projet_final_Force_N/blob/main/Exploration%20de%20donn%C3%A9es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. IMPORTATION DES LIBRAIRIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importation des données

In [7]:
df_malaria = pd.read_csv('/content/incidence-of-malaria.csv')
df_mortality = pd.read_csv('/content/maternal-mortality.csv')
df_prenatal = pd.read_csv('/content/share-of-mothers-receiving-at-least-one-antenatal-visit-during-pregnancy.csv')

In [17]:
df_malaria.head(50)

,Entity,Code,Year,Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations)
0,Afghanistan,AFG,1985,1910.3416,Asia,NaN
1,Afghanistan,AFG,1986,1602.9429,Asia,NaN
2,Afghanistan,AFG,1987,1586.7214,Asia,NaN
3,Afghanistan,AFG,1988,1413.9326,Asia,NaN
4,Afghanistan,AFG,1989,1382.7299,Asia,NaN

In [19]:
df_combined = df_malaria.merge(df_mortality, on=['Entity', 'Year'], how='outer')
df_combined = df_combined.merge(df_prenatal, on=['Entity', 'Year'], how='outer')

In [21]:
df_combined.head(50)

,Entity,Code_x,Year,"Incidence of malaria (per 1,000 population at risk)",Code_y,Maternal mortality ratio,World region according to OWID,Maternal mortality ratio (Annotations),Code,Pregnant women receiving prenatal care (%)
0,Afghanistan,NaN,1985,NaN,AFG,1910.34160,Asia,NaN,NaN,NaN
1,Afghanistan,NaN,1986,NaN,AFG,1602.94290,Asia,NaN,NaN,NaN
2,Afghanistan,NaN,1987,NaN,AFG,1586.72140,Asia,NaN,NaN,NaN
3,Afghanistan,NaN,1988,NaN,AFG,1413.93260,Asia,NaN,NaN,NaN
4,Afghanistan,NaN,1989,NaN,AFG,1382.72990,Asia,NaN,NaN,NaN
5,Afghanistan,NaN,1990,NaN,AFG,1377.85860,Asia,NaN,NaN,NaN
6,Afghanistan,NaN,1991,NaN,AFG,1392.78590,Asia,NaN,NaN,NaN
7,Afghanistan,NaN,1992,NaN,AFG,1451.59400,Asia,NaN,NaN,NaN
8,Afghanistan,NaN,1993,NaN,AFG,1368.81620,Asia,NaN,NaN,NaN
9,Afghanistan,NaN,1994,NaN,AFG,1375.09070,Asia,NaN,NaN,NaN
10,Afghanistan,NaN,1995,NaN,AFG,1400.84310,Asia,NaN,NaN,NaN
11,Afghanistan,NaN,1996,NaN,AFG,1375.51210,Asia,NaN,NaN,NaN
12,Afghanistan,NaN,1997,NaN,AFG,1365.28540,Asia,NaN,NaN,NaN
13,Afghanistan,NaN,1998,NaN,AFG,1459.28170,Asia,NaN,NaN,NaN
14,Afghanistan,NaN,1999,NaN,AFG,1359.21700,Asia,NaN,NaN,NaN
15,Afghanistan,AFG,2000,84.48,AFG,1346.14420,Asia,NaN,AFG,36.9
16,Afghanistan,AFG,2001,83.83,AFG,1273.43140,Asia,NaN,NaN,NaN
17,Afghanistan,AFG,2002,83.79,AFG,1277.30800,Asia,NaN,NaN,NaN
18,Afghanistan,AFG,2003,70.81,AFG,1196.09070,Asia,NaN,AFG,16.1
19,Afghanistan,AFG,2004,39.41,AFG,1114.88720,Asia,NaN,NaN,NaN
20,Afghanistan,AFG,2005,28.42,AFG,1102.80970,Asia,NaN,NaN,NaN
21,Afghanistan,AFG,2006,21.31,AFG,1044.40030,Asia,NaN,AFG,30.3
22,Afghanistan,AFG,2007,22.63,AFG,1023.49550,Asia,NaN,NaN,NaN
23,Afghanistan,AFG,2008,19.71,AFG,962.32150,Asia,NaN,AFG,36.0
24,Afghanistan,AFG,2009,12.97,AFG,913.03577,Asia,NaN,NaN,NaN
25,Afghanistan,AFG,2010,13.37,AFG,898.66920,Asia,NaN,AFG,59.6
26,Afghanistan,AFG,2011,15.99,AFG,883.71390,Asia,NaN,AFG,47.9
27,Afghanistan,AFG,2012,9.35,AFG,833.47720,Asia,NaN,AFG,51.2
28,Afghanistan,AFG,2013,11.45,AFG,820.68536,Asia,NaN,NaN,NaN
29,Afghanistan,AFG,2014,12.61,AFG,785.35406,Asia,NaN,AFG,63.2
30,Afghanistan,AFG,2015,14.10,AFG,775.69270,Asia,NaN,AFG,58.6
31,Afghanistan,AFG,2016,27.37,AFG,749.81570,Asia,NaN,NaN,NaN
32,Afghanistan,AFG,2017,28.99,AFG,681.80756,Asia,NaN,AFG,70.2
33,Afghanistan,AFG,2018,22.33,AFG,663.42750,Asia,NaN,AFG,65.2
34,Afghanistan,AFG,2019,14.15,AFG,644.27260,Asia,NaN,NaN,NaN
35,Afghanistan,AFG,2020,8.39,AFG,620.40753,Asia,NaN,NaN,NaN
36,Afghanistan,AFG,2021,6.26,NaN,NaN,NaN,NaN,NaN,NaN
37,Afghanistan,AFG,2022,9.19,NaN,NaN,NaN,NaN,NaN,NaN
38,Afghanistan,AFG,2023,13.26,NaN,NaN,NaN,NaN,NaN,NaN
39,Afghanistan,AFG,2024,17.76,NaN,NaN,NaN,NaN,NaN,NaN
40,Africa,NaN,1985,NaN,OWID_AFR,904.12787,NaN,NaN,NaN,NaN
41,Africa,NaN,1986,NaN,OWID_AFR,883.07526,NaN,NaN,NaN,NaN
42,Africa,NaN,1987,NaN,OWID_AFR,910.00190,NaN,NaN,NaN,NaN
43,Africa,NaN,1988,NaN,OWID_AFR,891.89160,NaN,NaN,NaN,NaN
44,Africa,NaN,1989,NaN,OWID_AFR,855.77460,NaN,NaN,NaN,NaN
45,Africa,NaN,1990,NaN,OWID_AFR,850.23047,NaN,NaN,NaN,NaN
46,Africa,NaN,1991,NaN,OWID_AFR,841.73444,NaN,NaN,NaN,NaN
47,Africa,NaN,1992,NaN,OWID_AFR,866.15560,NaN,NaN,NaN,NaN
48,Africa,NaN,1993,NaN,OWID_AFR,856.23830,NaN,NaN,NaN,NaN
49,Africa,NaN,1994,NaN,OWID_AFR,823.59766,NaN,NaN,NaN,NaN